package io.cdap.cdap.common.security.pqc.helpers;

import org.bouncycastle.jcajce.SecretKeyWithEncapsulation;
import org.bouncycastle.jcajce.spec.KEMGenerateSpec;
import org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.ByteBuffer;
import java.security.*;

/**
 * PQC Crypto Helpers -- ML-KEM-768 + AES-256-GCM hybrid encryption.
 *
 * Generated by Qryptive PQC Scanner. This file provides helper methods
 * for post-quantum hybrid encryption using ML-KEM (CRYSTALS-Kyber) for
 * key encapsulation and AES-256-GCM for symmetric encryption.
 *
 * Wire format: [kemCtLen (4 bytes)] [kemCt] [nonceLen (4 bytes)] [nonce] [ciphertext]
 */
public class PQCCryptoHelpers {

    private static final int GCM_NONCE_LENGTH = 12;
    private static final int GCM_TAG_LENGTH = 128;

    static {
        if (Security.getProvider("BCPQC") == null) {
            Security.addProvider(new BouncyCastlePQCProvider());
        }
    }

    /**
     * Hybrid encrypt: ML-KEM-768 key encapsulation + AES-256-GCM.
     *
     * @param publicKey The recipient's ML-KEM public key
     * @param plaintext The data to encrypt
     * @return Encoded bytes: [kemCtLen][kemCt][nonceLen][nonce][aesCt]
     */
    public static byte[] mlkem768HybridEncrypt(PublicKey publicKey, byte[] plaintext)
            throws GeneralSecurityException {
        // Key encapsulation
        KeyGenerator kemGen = KeyGenerator.getInstance("KYBER", "BCPQC");
        kemGen.init(new KEMGenerateSpec(publicKey, "AES"), new SecureRandom());
        SecretKeyWithEncapsulation encap = (SecretKeyWithEncapsulation) kemGen.generateKey();

        byte[] kemCiphertext = encap.getEncapsulation();
        SecretKey aesKey = new SecretKeySpec(encap.getEncoded(), 0, 32, "AES");

        // Symmetric encryption
        byte[] nonce = new byte[GCM_NONCE_LENGTH];
        new SecureRandom().nextBytes(nonce);

        Cipher aesCipher = Cipher.getInstance("AES/GCM/NoPadding");
        aesCipher.init(Cipher.ENCRYPT_MODE, aesKey, new GCMParameterSpec(GCM_TAG_LENGTH, nonce));
        byte[] ciphertext = aesCipher.doFinal(plaintext);

        // Pack: [kemCtLen][kemCt][nonceLen][nonce][ciphertext]
        ByteBuffer buf = ByteBuffer.allocate(4 + kemCiphertext.length + 4 + nonce.length + ciphertext.length);
        buf.putInt(kemCiphertext.length);
        buf.put(kemCiphertext);
        buf.putInt(nonce.length);
        buf.put(nonce);
        buf.put(ciphertext);
        return buf.array();
    }

    /**
     * Hybrid decrypt: ML-KEM-768 key decapsulation + AES-256-GCM.
     *
     * @param privateKey The recipient's ML-KEM private key
     * @param encoded    The encoded bytes from mlkem768HybridEncrypt
     * @return The decrypted plaintext
     */
    public static byte[] mlkem768HybridDecrypt(PrivateKey privateKey, byte[] encoded)
            throws GeneralSecurityException {
        ByteBuffer buf = ByteBuffer.wrap(encoded);

        // Unpack KEM ciphertext
        int kemCtLen = buf.getInt();
        byte[] kemCiphertext = new byte[kemCtLen];
        buf.get(kemCiphertext);

        // Unpack nonce
        int nonceLen = buf.getInt();
        byte[] nonce = new byte[nonceLen];
        buf.get(nonce);

        // Unpack AES ciphertext
        byte[] ciphertext = new byte[buf.remaining()];
        buf.get(ciphertext);

        // Key decapsulation
        KeyGenerator kemGen = KeyGenerator.getInstance("KYBER", "BCPQC");
        kemGen.init(new KEMGenerateSpec(privateKey, kemCiphertext, "AES"));
        SecretKeyWithEncapsulation decap = (SecretKeyWithEncapsulation) kemGen.generateKey();
        SecretKey aesKey = new SecretKeySpec(decap.getEncoded(), 0, 32, "AES");

        // Symmetric decryption
        Cipher aesCipher = Cipher.getInstance("AES/GCM/NoPadding");
        aesCipher.init(Cipher.DECRYPT_MODE, aesKey, new GCMParameterSpec(GCM_TAG_LENGTH, nonce));
        return aesCipher.doFinal(ciphertext);
    }
}
